config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root 'pokemons#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:pokename, :poketype, :pokeregion, :pokesize)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'pokemons', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!--- HEADER -->
<div class="header">
  <div class="title">
    <div class="titleimg">
      <%= image_tag "poke.png", class:"titlelogo"%>
    </div>
  </div>
</div>

<!--- STAGE -->
<div class="stage">
  <div class="board">
    <div class="showpoke">
        <div class="field">
          <%= form.label :pokename %>
          <%= form.text_field :pokename %>
        </div>

        <div class="field">
          <%= form.label :poketype %>
          <%= form.text_field :poketype %>
        </div>

        <div class="field">
          <%= form.label :pokeregion %>
          <%= form.text_field :pokeregion %>
        </div>

        <div class="field">
          <%= form.label :pokesize %>
          <%= form.text_field :pokesize %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>

        <%= link_to 'Show', @pokemon %> |
        <%= link_to 'Back', pokemons_path %>

    </div>  
  </div>
</div>

<% end %>

app/views/pokemons/edit.html.erb
<%= render 'form', pokemon: @pokemon %>

app/views/pokemons/index.html.erb
<!--- HEADER -->
<div class="header">
  <div class="title">
    <div class="titleimg">
      <%= image_tag "poke.png", class:"titlelogo"%>
    </div>
  </div>
</div>
<!--- STAGE -->
<div class="stage">
  <div class="board">
    <div class="showpoke">
      <p id="notice"><%= notice %></p>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Region</th>
            <th>Size</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @pokemons.each do |pokemon| %>
            <tr>
              <td class="pokelist"><%= pokemon.pokename %></td>
              <td class="pokelist"><%= pokemon.poketype %></td>
              <td class="pokelist"><%= pokemon.pokeregion %></td>
              <td class="pokelist"><%= pokemon.pokesize %></td>
              <td><%= link_to 'Show', pokemon, class:"pokelistlink" %></td>
              <td><%= link_to 'Edit', edit_pokemon_path(pokemon), class:"pokelistlink" %></td>
              <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' }, class:"pokelistlink" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="newpoke">
      <%= link_to 'New Pokemon', new_pokemon_path, class:"pokelistlink" %>
    </div>    

  </div>
</div>

app/views/pokemons/new.html.erb
<%= render 'form', pokemon: @pokemon %>

app/views/pokemons/show.html.erb
<!--- HEADER -->
<div class="header">
  <div class="title">
    <div class="titleimg">
      <%= image_tag "poke.png", class:"titlelogo"%>
    </div>
  </div>
</div>
<!--- STAGE -->
<div class="stage">
  <div class="board">
    <div class="showpoke">
      <p id="notice"><%= notice %></p>
      <p>
        <strong>Pokename:</strong>
        <%= @pokemon.pokename %>
      </p>

      <p>
        <strong>Poketype:</strong>
        <%= @pokemon.poketype %>
      </p>

      <p>
        <strong>Pokeregion:</strong>
        <%= @pokemon.pokeregion %>
      </p>

      <p>
        <strong>Pokesize:</strong>
        <%= @pokemon.pokesize %>
      </p>

      <%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
      <%= link_to 'Back', pokemons_path %>
    </div>  
  </div>
</div>